# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# plugins:
# vagrant plugin install vagrant-vbguest; vagrant plugin install vagrant-disksize

Vagrant.configure("2") do |config|
	#config.vm.box = "dev"
	config.vm.box = "kydreth/dev"
	config.vm.hostname = "sandobx"
	config.vm.provider "virtualbox" do |v|
		v.name="sandbox"
		v.memory=8192
		v.cpus=2
		v.customize ["modifyvm", :id, "--vram", "48"]
        v.customize ["modifyvm", :id, "--vram", "48"]
        v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        v.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
        v.customize ["storageattach", :id,
                        "--storagectl", "IDE",
                        "--port", "0", "--device", "1",
                        "--type", "dvddrive",
                        "--medium", "emptydrive"]
        v.gui = true # Display the VirtualBox GUI when booting the machine. In virtualbox while VM is off, set Display Graphics Controller to VBoxSVGA, and enable all acceleration options

	end
	
	#config.vm.network "private_network", ip: "10.0.0.0"
	#config.vm.network "forwarded_port", guest: 80, host: 80, id: "http"
	#config.vm.network "forwarded_port", guest: 443, host: 443, id: "https"
	config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1", id: "tomcat"
	config.vm.network "forwarded_port", guest: 8888, host: 8888, host_ip: "127.0.0.1", id: "Jupyter Notebook / Lab"
	config.vm.network "forwarded_port", guest: 5432, host: 5432, host_ip: "127.0.0.1", id: "postgresql db service"
	#config.vm.network "forwarded_port", guest: 8081, host: 8081, host_ip: "127.0.0.1", id: "postgresql adminer web"
	config.vm.network "forwarded_port", guest: 8082, host: 8082, host_ip: "127.0.0.1", id: "postgresql pgadmin4 web"
	config.vm.network "forwarded_port", guest: 9200, host: 9200, host_ip: "127.0.0.1", id: "elasticstack elasticsearch service"
	config.vm.network "forwarded_port", guest: 9200, host: 9300, host_ip: "127.0.0.1", id: "elasticstack nodes service"
	config.vm.network "forwarded_port", guest: 5601, host: 5601, host_ip: "127.0.0.1", id: "elasticstack kibana web"
	config.vm.network "forwarded_port", guest: 4200, host: 4200, host_ip: "127.0.0.1", id: "nodejs angularjs web"
	config.vm.network "forwarded_port", guest: 3000, host: 3000, host_ip: "127.0.0.1", id: "nodejs reactjs web"

	config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
	#vagrant virtualbox errors found: /var/log/vboxadd-setup.log

end
