# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# plugins:
# vagrant plugin install vagrant-vbguest; vagrant plugin install vagrant-disksize

$config_git = <<SCRIPT
git config --global core.autocrlf input

SCRIPT

#https://github.com/spring-guides/gs-rest-service
$setup_git_repo_java_spring = <<SCRIPT
cd /home/vagrant
git clone --quiet https://github.com/spring-guides/gs-rest-service.git
cd gs-rest-service/complete
sudo ./gradlew build

SCRIPT
#TODO: make service
#./gradlew bootRun &
# access via http://localhost:8080/greeting

$setup_git_repo_angularjs = <<SCRIPT
cd /home/vagrant
curl -sL "https://angular.io/generated/zips/toh-pt6/toh-pt6.zip" -O
unzip -q toh-pt6.zip -d tourofheroes
cd tourofheroes
npm install -s -n >>/dev/null
npm run -s build >>/dev/null
cd /vagrant
sudo cp tourofheroes.service /etc/systemd/system/tourofheroes.service
sudo systemctl enable tourofheroes.service
sudo systemctl start tourofheroes.service

SCRIPT


#https://github.com/creativetimofficial/nextjs-material-kit.git
#https://github.com/clintonwoo/hackernews-react-graphql
$setup_git_repo_reactjs = <<SCRIPT
cd /home/vagrant
git clone --quiet https://github.com/creativetimofficial/nextjs-material-kit.git
cd nextjs-material-kit
npm install -s -n >>/dev/null
npm run -s build >>/dev/null
cd /vagrant
sudo cp reactjs.service /etc/systemd/system/reactjs.service
sudo systemctl enable reactjs.service
sudo systemctl start reactjs.service

SCRIPT

Vagrant.configure("2") do |config|
	config.vm.box = "dev"
	config.vm.hostname = "sandobx"
	config.vm.provider "virtualbox" do |v|
		v.name="sandbox"
		v.memory=8192
		v.cpus=2
		v.customize ["modifyvm", :id, "--vram", "48"]
        v.customize ["modifyvm", :id, "--vram", "48"]
        v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        v.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
        v.customize ["storageattach", :id,
                        "--storagectl", "IDE",
                        "--port", "0", "--device", "1",
                        "--type", "dvddrive",
                        "--medium", "emptydrive"]
        v.gui = true # Display the VirtualBox GUI when booting the machine. In virtualbox while VM is off, set Display Graphics Controller to VBoxSVGA, and enable all acceleration options

	end
	
	#config.vm.network "private_network", ip: "10.0.0.0"
	#config.vm.network "forwarded_port", guest: 80, host: 80, id: "http"
	#config.vm.network "forwarded_port", guest: 443, host: 443, id: "https"
	config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1", id: "tomcat"
	config.vm.network "forwarded_port", guest: 8888, host: 8888, host_ip: "127.0.0.1", id: "Jupyter Notebook / Lab"
	config.vm.network "forwarded_port", guest: 5432, host: 5432, host_ip: "127.0.0.1", id: "postgresql db service"
	#config.vm.network "forwarded_port", guest: 8081, host: 8081, host_ip: "127.0.0.1", id: "postgresql adminer web"
	config.vm.network "forwarded_port", guest: 8082, host: 8082, host_ip: "127.0.0.1", id: "postgresql pgadmin4 web"
	config.vm.network "forwarded_port", guest: 9200, host: 9200, host_ip: "127.0.0.1", id: "elasticstack elasticsearch service"
	config.vm.network "forwarded_port", guest: 9200, host: 9300, host_ip: "127.0.0.1", id: "elasticstack nodes service"
	config.vm.network "forwarded_port", guest: 5601, host: 5601, host_ip: "127.0.0.1", id: "elasticstack kibana web"
	config.vm.network "forwarded_port", guest: 4200, host: 4200, host_ip: "127.0.0.1", id: "nodejs angularjs web"
	config.vm.network "forwarded_port", guest: 3000, host: 3000, host_ip: "127.0.0.1", id: "nodejs reactjs web"

	config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
	#vagrant virtualbox errors found: /var/log/vboxadd-setup.log
	config.vm.provision "shell", inline: $config_git, privileged: false
	config.vm.provision "shell", inline: $setup_git_repo_java_spring, privileged: false
	config.vm.provision "shell", inline: $setup_git_repo_angularjs, privileged: false
	config.vm.provision "shell", inline: $setup_git_repo_reactjs, privileged: false

end
