# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# plugins:
# vagrant plugin install vagrant-vbguest; vagrant plugin install vagrant-disksize

$setup_os = <<SCRIPT
yum update -y -q -e 0
yum install -y -q -e 0 git vim wget pushd popd bzip2 zip unzip nano less dnsutils nc telnet
yum groupinstall -y -q -e 0 "GNOME Desktop" --setopt=group_package_types=mandatory,default,optional
systemctl set-default graphical.target
systemctl start graphical.target
#TODO: scan and patch OS (STIG: ?; SCAP Guide: https://static.open-scap.org/ssg-guides/ssg-centos7-guide-index.html)
yum clean all
cat /dev/null > ~/.bash_history && history -c && exit

SCRIPT

Vagrant.configure("2") do |config|
	config.vm.box = "centos/7"
	#config.vm.box_version = "1905.1"
	#config.vm.box = "plus3it/spel-minimal-centos-7" #https://app.vagrantup.com/plus3it/boxes/spel-minimal-centos-7
	config.vm.hostname = "base"
	config.vm.provider "virtualbox" do |v|
		v.name="base"
		v.memory=8192
		v.cpus=2
		v.customize ["modifyvm", :id, "--vram", "48"]
		v.gui = true # Display the VirtualBox GUI when booting the machine
	end

	config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
	#vagrant virtualbox errors found: /var/log/vboxadd-setup.log
	config.vm.provision "shell", inline: $setup_os

end
