# PostgreSQL Docker Compose File
version: '3.3'
services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    restart: always
    networks:
      - postgresql
#    command:
#      - "postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/tmp/logs"
#      - "postgres -c config_file=/etc/postgresql.conf"
    volumes:
      - postgresql:/var/lib/postgresql/data
#      - ./data:/var/lib/postgresql/data
#      - ./postgresql.conf:/etc/postgresql.conf
#      - ./logs:/tmp/logs
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-jskszUT4z7uJ4MhY}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
#  adminer:
#    image: adminer
#    container_name: adminer
#    restart: always
#    ports:
#      - 8081:8080
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    networks:
      - postgresql
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-pgadmin}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-jskszUT4z7uJ4MhY}
      - PGADMIN_LISTEN_ADDRESS:"127.0.0.1"
      - PGADMIN_LISTEN_PORT:80
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
      - PGADMIN_CONFIG_LOGIN_BANNER="This is running in Docker, via Vagrant and VirtualBox!"
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10
    ports:
      - 8082:80
volumes:
  postgresql:
    driver: local
networks:
  postgresql:
    driver: bridge
