#Elastic Stack https://www.elastic.co/guide/en/elastic-stack-get-started/current/get-started-docker.html
version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elasticstack
    command: >
      /bin/sh -c "./bin/elasticsearch-plugin install ingest-attachment;
      /usr/local/bin/docker-entrypoint.sh"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.1
    container_name: kibana
    restart: always
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL:"http://elasticsearch:9200"
      - ELASTICSEARCH_HOSTS:"http://elasticsearch:9200"
    networks:
      - elasticstack

volumes:
  data01:
    driver: local

networks:
  elasticstack:
    driver: bridge
